version: '3.4'

services:
  productreaderservice:
    image: productreaderservice:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ProductReaderService"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_productreaderservice$
    volumes:
      - C:\Users\PRIME\Desktop\CoreTraining\DockerSample\ProductReaderService:/app
      - C:\Users\PRIME\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_productreaderservice$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_productreaderservice$ \"bin/Debug/netcoreapp2.2/ProductReaderService.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""

  productupdateservice:
    image: productupdateservice:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ProductUpdateService"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_productupdateservice$
    volumes:
      - C:\Users\PRIME\Desktop\CoreTraining\DockerSample\ProductUpdateService:/app
      - C:\Users\PRIME\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_productupdateservice$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_productupdateservice$ \"bin/Debug/netcoreapp2.2/ProductUpdateService.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""

